### ISSUE TITLE
Can't delete polls

### ISSUE THREAD

**Issue by newdeltaart** [KazuAlex/openpollslack#15]
Can't delete polls from Slack message or group. Super frustrating.

**Comment by KazuAlex** [comment]
The poll is like a message. So you need the write to delete message to delete poll.
Do you have it ?

**Comment by newdeltaart** [comment]
It's my channel, so I should have the right to delete but it's not an option. I have a few polls posted on it that had mistakes so the channel is looking nasty and I'm confusing my team, but there's no way to get rid of them that I'm seeing.

**Comment by KazuAlex** [comment]
Probably your Slack's configuration.
Go to "Settings & administration" > "Permissions" tab and expand "Message Editing & Deletion". You probably configure "Allow editing:" to a value different from "Any time"

**Comment by KazuAlex** [comment]
Hey @newdeltaart, are you ok with message deletion ?

**Comment by KazuAlex** [comment]
Reopen the issue if you are sure the problem is with the application and not Slack itself.
