### ISSUE TITLE
Can only post polls in public channels

### ISSUE THREAD

**Issue by prensing** [KazuAlex/openpollslack#16]
Sorry, I feel foolish opening an Issue for this, but there does not seem to be any way to ask simple questions.

Is there a way to test drive the app without self-hosting? I followed the links to install it into Slack, but then nothing happens. I assume this is because I need a hosting site. I can do that, but I would like to see it working a bit before spending the time.

It does seem like a good tool.

**Comment by KazuAlex** [comment]
Hi @prensing 

I didn't realize there was no link to my instance in slack.

Feel free to test it : https://openpoll.slack.alcor.space/
This is my "website" that give you the link to add my instance to your slack workspace.

**Comment by prensing** [comment]
Hmm, yes, I had tried that; it shows up if you add OpenPoll from the Slack App Catalog. It seems to claim it installed, but when I try "/openpoll a b c" in my SlackBot channel, it does not recognize "/openpoll".

**Comment by KazuAlex** [comment]
It's not "/openpoll" but "/poll" ;)
I've not updated readme, sorry :(

**Comment by prensing** [comment]
Still, hmm. I suspect it was colliding with other poll apps (I am looking for a better one). I removed all of them, and then re-added OpenPoll. Now if I start "/poll" I do get the help message from OpenPoll (clearly marked), but when I type in a poll and then hit enter, it just vanishes and nothing comes back (no output).

**Comment by KazuAlex** [comment]
Maybe have you a mac that modify " character ?
Try with this with a copy/paste : /poll "What's your favourite color ?" "Red" "Green" "Blue" "Yellow"
Also you can try using the modal : 
![image](https://user-images.githubusercontent.com/7015549/89571588-36543080-d828-11ea-99f3-32d028d1cad3.png)

**Comment by prensing** [comment]
OK, got it. FYI, I am using a Linux desktop. 

The issue is that the App cannot seem to create a poll in anything but a public channel. I was testing in #slackbot (or my DM channel) and that does not work. Also seems to fail in a private channel.

**Comment by KazuAlex** [comment]
Thanks for your feedback.

I will keep this issue opened to try to allow app to post in private channel and dm (not sure about dm)

**Comment by prensing** [comment]
Private channels is definitely a useful feature. In our Slack we have a few big groups which are private, and I could definitely see wanting a poll within such a channel. I agree DMs is not so useful; however, it is convenient to test creating a polling in the Slackbot channel before doing it for real.

**Comment by KazuAlex** [comment]
Hi @prensing 
FYI, it's an authorization scope issue. I've updated it but need a slack review :(
Probably reviewed in 1 or 2 days. Maybe 7. I will keep you updated here.

**Comment by shaskin-rls** [comment]
Hey @KazuAlex - Thanks for the app! I just got it today and tried to post to a private channel. It still didn't work for me unfortunately. I even tried inviting the app to the private channel, and it still didn't work. Any updates here? Thanks again!

**Comment by KazuAlex** [comment]
Sorry but slack wouldn't accept my request with adding new scope to access to private channels.
For them, you need to invite the bot inside the channel with `/invite @openpoll`...
I'm not sure if this will work in private DM

**Comment by dlealv** [comment]
I am looking for how to use /invite command and to add open poll as a bot, I was not able to find this information anywhere, I was trying some options with no success. Thanks for any help on this.

**Comment by KazuAlex** [comment]
You need to type /invite and start typing @openpoll
You will have an autocomplete list with people and "bot users". Choose the bot "Openpoll"
It's not impossible that your organization remove the ability for you to add bot users into a channel

But, it's only works with private **channels**. Not DM.
For DM, you need to create new DM with Open Poll at creation
