### ISSUE TITLE
Editing & Deleting Polls

### ISSUE THREAD

**Issue by DHStom** [KazuAlex/openpollslack#17]
Maybe I am just missing something, but after posting a poll with a typo (d'oh!) I could not find a way to either edit the poll I posted nor could I delete the poll.

Am I missing something? If not, are those options on the feature list for the future?

**Comment by KazuAlex** [comment]
Hey @DHStom 
This is OK for you ? Can i close this issue ?

**Comment by DHStom** [comment]
Yes, thank you.
