### ISSUE TITLE
Limit polls: change vote without removing previous vote

### ISSUE THREAD

**Issue by tcn33** [KazuAlex/openpollslack#18]
Currently, if there is a vote limit, then the voter must remove their vote(s) in order to revote.

An enhancement would be to have the new vote simply replace the previous vote, i.e instead of silently failing, the new vote is accepted and the previous vote disappears.

Happy to submit a PR if you're accepting them.

**Comment by KazuAlex** [comment]
The voter not must to do this. Not in my mind. I can add a message to warn user about vote limit reach. But I think there is not a good idea to remove user's vote without warn it before.
We can consider adding an option to remove older vote but by default, the app will keep current behaviour. But If in future many people ask for this default behaviour, I could reconsider my choice !

Feel free to create a PR ;)
