### ISSUE TITLE
Enable bot direct messaging

### ISSUE THREAD

**Issue by mattrossman** [KazuAlex/openpollslack#21]
I understand from #16 that the bot is limited to public channels, but could we have the bot "messages" tab enabled so users can test out the polling features in a private setting?

Currently when I try to message the bot, I get a message saying the feature is disabled

![image](https://user-images.githubusercontent.com/22670878/98587459-2bca8c80-2298-11eb-923d-9234d1453d22.png)

[Polly](https://mshci-gt.slack.com/apps/A04E6JX41-polly) is one example of a similar app that has the messages tab enabled.

**Comment by KazuAlex** [comment]
I've done the changes but slack need to review this option... be patient (from 2 to 4 weeks...)

**Comment by KazuAlex** [comment]
It's live !
