### ISSUE TITLE
Change "authored by" emoji

### ISSUE THREAD

**Issue by aph3rson** [KazuAlex/openpollslack#23]
Right now, Open Poll uses `:eyes:` to show who requested a poll be created in a channel. This implies more "who has seen this poll?" and not "who created this poll?," which could be confusing for new users.

Using something like `:writing_hand:` has more of an implication of "who wrote this?" in my opinion, and might make a better emoji.

This should be pretty straightforward to do, and would only require changing this line: https://github.com/KazuAlex/openpollslack/blob/67cc329b681c1ac70747e24c51fdc127d49e8c6d/index.js#L744

**Comment by aph3rson** [comment]
I'd be more than happy to open a PR for this, figured I'd bounce it as an idea first.

**Comment by KazuAlex** [comment]
Nice idea. But this repository is a mirror for gitlab repo.
Please open a MR on gitlab instead :) I can do the change if you don't have a gitlab account

**Comment by KazuAlex** [comment]
Done & live :)
