### ISSUE TITLE
adding limit appears to be broken and causes a poll to not be created.

### ISSUE THREAD

**Issue by HappyZombies** [KazuAlex/openpollslack#25]
Making a poll with the command line args of "limit 1" seems to not create the poll at all. Having no limit seems to be ok and creates the poll fine. Normally I'd have some error but uh, sorry this is the behavior I am experiencing, and I have the bot up to date!

**Comment by KazuAlex** [comment]
@HappyZombies can you send me the full command ?
This command `/poll limit 1 "What's you favourite color ?" "Red" "Green" "Blue" "Yellow"` seems to work great :)

**Comment by HappyZombies** [comment]
@KazuAlex ah! it appears that I add the limit at the end of the command... 

`/poll "Delete me" "yes" limit 1`

I recall doing this before and it working!

**Comment by KazuAlex** [comment]
> I recall doing this before and it working!

Not sure about that.

I close the issue and keep in mind to improve the command parser to get options at the end of the command ;)

**Comment by HappyZombies** [comment]
Huh guess my memory is off, but thanks for clarifying that! Much appreciated :)
