### ISSUE TITLE
/poll failed with the error "dispatch_failed" after latest update

### ISSUE THREAD

**Issue by Tepsie** [KazuAlex/openpollslack#27]
We can no longer make polls and receive a "dispatch_failed" message.

Have repro'd on both Web and Desktop apps. It doesn't matter if their are one or multiple answer options.

**Comment by KazuAlex** [comment]
Solved. This is a server issue :)

**Comment by ValdarT** [comment]
Seems to be back.

**Comment by KazuAlex** [comment]
No problem for me. What are you typing after /poll or use you the modal ?

**Comment by ValdarT** [comment]
Got the response when I tried with the example: `/poll “What’s you favourite color ?” “Red” “Green” “Blue” “Yellow”`

**Comment by ValdarT** [comment]
Tried in both a public and private channel with the bot added in both cases.

**Comment by KazuAlex** [comment]
I really have no idea. Try to remove and reinstall the app ?

**Comment by Tepsie** [comment]
Stopped working again today.
I tried to reinstall the app but that doesn't seem to fix it. Any suggestions?

**Comment by KazuAlex** [comment]
Seems to be OK server side. Did you have any error ?
What is not working ? create a poll ? from modal or with /poll command ?
