### ISSUE TITLE
Anoymous and Limit flags don't work

### ISSUE THREAD

**Issue by unknowndomain** [KazuAlex/openpollslack#3]
Using this and the example from the readme.md 

/openpoll anonymous limit “What is best?” “Cats” “Dogs”

These flags don't work you can still see who voted at both ends, and you can vote multiple times

**Comment by KazuAlex** [comment]
Hello @unknowndomain 
Thanks for reporting this issue.

This is probably due to the mac replacements quotes... It's working great with correct quotation mark ( " ) ... use this for the moment and i'll investigate on it soon.

**Comment by unknowndomain** [comment]
So the solution might be here:
https://github.com/KazuAlex/openpollslack/blob/706e97278e3bebd5bd2b7ac94a4fc6da34589b58/index.js#L145

To either do a string replace to replace these quotes, or to change the pattern to include the other two types of quote marks?

**Comment by KazuAlex** [comment]
I know exactly where is the problem (outside of macOS). This is my shitty code :D

**Comment by KazuAlex** [comment]
Hi @unknowndomain 
I've fixed that. You can check the commit ( 13f1d53c741e563ca35f5ce8de8e09f2f97f10c8 ) :)

**Comment by unknowndomain** [comment]
Perfect!
