### ISSUE TITLE
Hidden shows all votes even if limit

### ISSUE THREAD

**Issue by bmccarthynn** [KazuAlex/openpollslack#30]
If you create a new poll that is both hidden and limited, the limited votes are revealed. To recreate:

1. Create new hidden and limit poll: 
`/poll hidden limit 1 "What's you favourite color ?" "Red" "Green" "Blue" "Yellow"`
2. Vote for both red and green. An message will display "You can't vote anymore..." after green Vote is clicked.
3. Click "Reveal the votes"

**Expected Result:** Only the valid votes are visible.
**Actual Result:** All votes beyond the limit are visible.

**Before Reveal:**
![image](https://user-images.githubusercontent.com/72044262/148608913-c9a40cd2-9578-42b5-8fc3-1fd65e488ba0.png)

**After Reveal:**
![image](https://user-images.githubusercontent.com/72044262/148609005-cddee698-0502-48b3-b208-f303abef736c.png)

**Comment by KazuAlex** [comment]
I will take a look soon. Maybe you have clicked too quickly on Red and Green buttons ?

**Comment by bmccarthynn** [comment]
Waited 10 seconds between clicking Red then Green. Either way, on clicking Green, it knows Red was already clicked/voted based on the "You can't vote anymore." Also, not sure how to "Remove a vote to choose another option." as there is no UI element to remove a vote. Screencast: https://share.getcloudapp.com/RBuyqq81

**Comment by KazuAlex** [comment]
Fixed!
