### ISSUE TITLE
Token Revokes Every 24 hours?

### ISSUE THREAD

**Issue by iDorosh** [KazuAlex/openpollslack#34]
I install the slack app, everything works fine. But after 24 hours I hit an authorization error with bolt. Am I missing something here or does something need to be implemented to refresh the token in case of an expired one?

`bolt-app Authorization of incoming event did not succeed. No listeners will be called.`

**Comment by KazuAlex** [comment]
What are you talking ? "insatlled" like using my instance or "installed" your own instance ?

For the second option: https://github.com/slackapi/bolt-js/issues/811
Have you modified the code for "installation" ?
Your scopes are correct ?

**Comment by iDorosh** [comment]
Oh sorry should have been more specific. I cloned the project and I am hosting it in Heroku. The only thing I updated in the JS file was to pull variables from heroku instead of a file. 

Looking into the JS script seems like the only scope that I don’t have implemented is groups:write.
Would that be the cause?

**Comment by KazuAlex** [comment]
I don't think the `groups:write` scope is the problem.
can you access to the "database" file (config/open_poll.json) to check if your slack organisation/team is always registered inside ?
If is inside, check there are a token like `"token":"xoxb-yyyyyyyyy..."`

**Comment by iDorosh** [comment]
I can’t access the file, but I think your question made me realize what might be happening. 
 I am kinda new to heroku and seems like every 24 hours the Dyno restarts and wipes and created files. This is probably the issue

**Comment by KazuAlex** [comment]
Yeap, maybe that!
I close the issue, but reopen it if you need.
