### ISSUE TITLE
List of voters?

### ISSUE THREAD

**Issue by asadakbar** [KazuAlex/openpollslack#4]
Hi, I'm looking into using this and wanted to know if there was a way to get a list of the people that voted on the poll. I wanted to use this as a single item "I completed the item" checklist, and think this may be a good way of doing it. 

Ideally I could add a list of people that need to complete it and would have a slash command that would give me the folks that have yet to complete.

**Comment by KazuAlex** [comment]
Hi @asadakbar 
Sorry for the delay.

If your poll is not anonymous, the list of people who voted for an item are under the vote line.

For the slash command, it's not possible. I don't save any informations on my server (except error logs). So, i can't retrieve any informations about a poll except with the actions provided in message (like the "vote" buttons).
I'm not really excited about a new feature for limiting the vote to a list of users. But you can do the stuff by forking this repo. You can do a pull request and i'll see to integrate it.

Reopen this issue if you want to discuss more about that.
