### ISSUE TITLE
Openpoll with more customizable, translatable, allow others to add add choices

### ISSUE THREAD

**Issue by polppol** [KazuAlex/openpollslack#43]
Hi,
I just make Open Poll more customizable, translatable, allow others to add choices
and I also modified how it response to Slack to let Open Poll post a poll in private chanel without adding Bot in that chanel 
(using /command or Modal that open by /command only, not shortcut)
my fork is here
https://github.com/polppol/openpollslack-i18n

Please note that this fork will add some complexity to the App
If you dont need any of these it is a good idea to stay in orginal App.

Summary of additional features:
- Allow choices add by others
- True Anonymous Vote (Poller can't see users votes if this mode is ON) : Default ON
- Notice if True Anonymous Vote is OFF (As poller can see other member votes)
- Customizeable UI (Order, Show/Hide Element you don't want to make it cleaner)
- UI Language, Multiple language support
- Separate configuation for each Slack team(You can turn on/off any features)
- Better error handling that may crash the server

**Comment by KazuAlex** [comment]
Hi,

I want to keep Open poll as simple as it is. No too complex features or nothing that the user can say "what is this ?"
But translations are a great feature. I will try to implement it in my version (or if you want to create a PR you're welcome, I can pick up it from github and recreate it on gitlab, but not merge it directly on )
I already try to respond without being part of the channel (or DM). But it appears that I need another permission that slack denied me.

Thanks for creating a fork! :)
I will pin this issue for interested people.
