### ISSUE TITLE
[Feature Request] Add Note to Users about Anonymous Voting

### ISSUE THREAD

**Issue by gborillo-dev** [KazuAlex/openpollslack#45]
When using anonymous feature (it's great) the users can vote and removes clutter of the names on the UI but the user might also have the impression that the vote is submitted in confidence. The poller have an option to see the votes (users who voted). 

As a user that is submitting my vote or answering an anonymous poll, I should know that the poller (creator of the poll) can see who submitted poll/vote so that I know that my submission is not truly anonymous.

"Thanks for your hard work on this! Thank you!"

**Comment by polppol** [comment]
Hi,
You could add following code between line 1500 and 1501 of current commit https://github.com/KazuAlex/openpollslack/commit/9612d07710440bfbfcad6de5fd9d0dfccf42f77d
```
let addInfo = ''; //Other message (if any) 
if(isAnonymous) {
	if(addInfo!=="") addInfo += "\n";
	addInfo += 'NOTE: Poll creator still can see who voted which options';
}
if(addInfo!=="") {
	blocks.push({
	  type: 'context',
	  elements: [{
		type: 'mrkdwn',
		text: addInfo,
	  }],
	});
}
```

I also implement this in my own fork if you would like to test it,
unfortunately I do a lot of other modification in my fork so it way too complex to do PR the whole thing to this repo with out his or her permission.

**Comment by davidknapp** [comment]
Awesome contribution @polppol ! I would prefer this tested and in main branch. @KazuAlex could you test/merge this update into the OpenPoll App available in the Slack App directory? Current version OpenPoll Slack App is using the term anonymous _but_ the poll owner can view all of the names of the "anonymous" poll answeres. This is a problem as OpenPoll is presenting false information and false expectations of privacy for the poll answerer. This dis-information is putting usage and installations of OpenPoll at risk for every customer that uses the latest version.

**Comment by polppol** [comment]
Hi,
I Just submit PR https://github.com/KazuAlex/openpollslack/pull/46 to main branch

PS. My test/dev branch is here (https://github.com/polppol/openpollslack-i18n)
It will contain other feature/modification but you can test any of them by using `/poll config` to turn on or off features.

**Comment by KazuAlex** [comment]
Hi guys!
Sorry for the late response.

I can't merge PR here. Because github is only a miror for the main repo in gitlab.
Also, why adding note ? I prefer not showing the voters to the poll creator.
Will make changes this week to apply this modifications.

**Comment by davidknapp** [comment]
thanks @KazuAlex I moved it over to Gitlab: https://gitlab.com/openpollslack/openpollslack/-/issues/33

**Comment by KazuAlex** [comment]
https://gitlab.com/openpollslack/openpollslack/-/issues/33

> Hey !
> This way increase block number and slack limit the number of block in one message. Also, anonymous poll need to be fully > anonymous.
> I've merged this feature that prevent user to see users vote on anonymous.

**Comment by sinchan1987** [comment]
@KazuAlex  we cannot see the changes reflected on our end after you merged the changes to the main branch. Does the app need to be re-installed to see the changes?
