### ISSUE TITLE
Unable to create polls or vote on existing ones

### ISSUE THREAD

**Issue by mrshauneeb** [KazuAlex/openpollslack#52]
Error when creating a poll - /poll failed with the error “dispatch_unknown_error”

Is something down?

**Comment by j4r3kb** [comment]
https://openpoll.slack.alcor.space/ ERR_CONNECTION_REFUSED for me

**Comment by KazuAlex** [comment]
My vps provider have fucked up my instance. So I need to migrate to new one.

I'm working on it.

Will update you soon.

**Comment by KazuAlex** [comment]
Service will slowly come back for all.

Don't hesitate to try your old polls and send me feedback if all is OK
Also, don't know why sometimes creating poll or voting on it failed. Maybe due to slack's dns cache. Retrying 2-3 times working for me.
I'll monitoring logs
