### ISSUE TITLE
Poll is not registering votes when limit is set

### ISSUE THREAD

**Issue by muttleyxd** [KazuAlex/openpollslack#6]
Probably related to #5 

```
/openpoll "Question" "Answer 1" "Answer 2"
```
will work fine, however:

```
/openpoll limit 1 "Question" "Answer 1" "Answer 2"
```
doesn't work properly. Clicking Vote on any button doesn't do anything when limit is set.

**Comment by KazuAlex** [comment]
Hi @muttleyxd 

Thanks you for the report.

I'll fix it today.

**Comment by KazuAlex** [comment]
Hi @muttleyxd 

It was related to #5 and it's now fixed.

Thanks for using this app ! :)

**Comment by muttleyxd** [comment]
Works now, thanks, it's a great app!
