### ISSUE TITLE
Ranked Choice Voting option?

### ISSUE THREAD

**Issue by karlbecker** [KazuAlex/openpollslack#8]
Hello,
Any interest in having a Ranked Choice Voting option for polls? 

I'm interested in building one to help more people discover the joy and efficiency of ranked choice voting, so just wondering if you'd be interested in having that as part of this tool.

Cheers,
Karl

**Comment by KazuAlex** [comment]
Hello Karl,

It is a really idea. But i want to keep this plugin very simple to use. If we add more complexity to choose an option, i'm not sure about this.
I have also the question about how to show the responses.
You can take a look at this : https://api.slack.com/tools/block-kit-builder
This is the block builder for slack app that limit our message customisation.
