### ISSUE TITLE
Polls with many answers do not work

### ISSUE THREAD

**Issue by genesys2** [KazuAlex/openpollslack#9]
Hi,

I found an error when you do a poll with many answers. After a certain legth of the poll, voting does not seem to work anymore (indicated by a small /!\ after pressing vote).

Here is a poll which demonstrates the problem:
````/openpoll "A question which allows many answers..." "Lalala" "Lalala" "Lalala" "Lalala"  "Lalala" "Lalala" "Lalala" "Lalala" "Lalala" "Lalala" "Lalala" "Lalala" "Lalala " "Lalala " "Lalala "````

**Comment by KazuAlex** [comment]
Hi @genesys2 

Thank you for the report. I'll investigate on this soon !

**Comment by KazuAlex** [comment]
Hello @genesys2 

It looks like resolved.
I had some problems with my hosting. But it's now OK.

Thanks for the report and don't hesitate to reopen the issue if you still have the problem.
